import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/context/AuthContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Learn AO",
  description: "Generated by create next app",
};

declare global {
  interface Window {
    arweaveWallet: {
      connect: () => Promise<any>;
      disconnect: () => Promise<any>;
      signMessage: (message: any) => Promise<any>;
      getActiveAddress: () => Promise<string>;
      getActivePublicKey: () => Promise<string>;
    };
  }
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
